### ISSUE TITLE
Critical error: negative currency not allowed

### ISSUE THREAD

**Issue by fab-io** [NebulousLabs/Sia#1529]
Running Sia 1.0.4
```
Critical error: negative currency not allowed
Please submit a bug report here: https://github.com/NebulousLabs/Sia/issues
goroutine 93688 [running]:
runtime/debug.Stack(0x7a, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Critical(0xc42e4445b0, 0x1, 0x1)
        /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:19 +0xb7
github.com/NebulousLabs/Sia/types.Currency.Sub(0xc420120a00, 0x0, 0x0, 0x0, 0x0, 0xc432981140, 0x2, 0x5, 0x0, 0x0, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/types/currency.go:183 +0x16c
github.com/NebulousLabs/Sia/modules/host.(*Host).removeStorageObligation(0xc4202b6100, 0xdae0b8, 0x0, 0x0, 0x0, 0xc432981140, 0x2, 0x5, 0x0, 0xc432981170, ...)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:528 +0x1ca0
github.com/NebulousLabs/Sia/modules/host.(*Host).threadedHandleActionItem(0xc4202b6100, 0xdd75cb2b0505aa3e, 0x6aea30a358f92b4f, 0x2ba5294c49f3fc82, 0x3018102fbbc64d5a, 0xc43ddc64f0)
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/storageobligations.go:671 +0x2ebf
created by github.com/NebulousLabs/Sia/modules/host.(*Host).ProcessConsensusChange
        /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/update.go:309 +0x249

```

**Comment by lukechampine** [comment]
These errors are generally benign. It means that the host tried to subtract some number of siacoins and it underflowed. So your hosting metrics may be skewed a little, but it won't affect anything important.
We have a fairly large host refactor open (#1501), so we can revisit this bug if it's reproducible after the refactor is merged.
Thanks!

**Comment by DavidVorick** [comment]
I don't think that the refactor touches this bug, but I have a decent idea of what is causing the failure. I'll open this until I believe I have fixed the root cause.

But as @lukechampine it's just an accounting thing, the host is incorrectly computing revenue.

**Comment by fab-io** [comment]
Now I'm getting this error on day basis, and to me seems that after it the host.log file freeze

is there any more info that you may need in order to debug it?

here my host.log last lines
```

2017/01/01 15:31:49.531672 storageobligations.go:527: Rejecting storage obligation expiring at block 85072, current height is 85075. Potential revenue is 467590384821153409884225536.
2017/01/01 16:39:30.645876 storageobligations.go:669: Full time has elapsed, but the revision transaction could not be submitted to consensus, id eb037ba88b0446134844477d63253e179ff9f3651e51153a07106ddd7f6468ae
2017/01/01 16:39:30.645939 storageobligations.go:527: Rejecting storage obligation expiring at block 85077, current height is 85080. Potential revenue is 437588916814753412937678848.
2017/01/03 20:50:11.335568 host.go:258: SHUTDOWN: Logging has terminated.
2017/01/03 20:51:47.416140 dependencies.go:105: STARTUP: Logging has started.
2017/01/03 20:51:47.451836 persist.go:182: WARN: NetAddress '' loaded from persist is invalid: missing port in address
2017/01/03 20:52:03.250356 upnp.go:109: WARN: could not automatically forward port 9982: no UPnP-enabled gateway found
2017/01/03 20:52:03.250396 network.go:85: ERROR: failed to forward port: no UPnP-enabled gateway found
2017/01/04 23:16:11.745186 storageobligations.go:669: Full time has elapsed, but the revision transaction could not be submitted to consensus, id 8b231b553aa60fd19f2675c62ea33828e302f4dd1198631699978123482d5ca8
2017/01/04 23:16:11.761466 storageobligations.go:527: Rejecting storage obligation expiring at block 85576, current height is 85579. Potential revenue is 437588916814753412937678848.

```

**Comment by DavidVorick** [comment]
Yeah I think that error is appearing as you complete your contracts. It will keep producing annoying output. Unfortunately I'm not sure there's much we can do in the short term, I'm not even sure there's a way to clear the inconsistent state within your machine that's causing the problems.

I will reiterate that I'm 90% confident it's purely a cosmetic bug - it thinks it has 0 revenue when it's actually got revenue (revenue which IS hitting the wallet, despite the host's confusion). Therefore it's fairly low priority vs. v1.1 coming out in January.

But we will do our best to have this fixed in v1.2 (Feb-March target)

**Comment by lukechampine** [comment]
@DavidVorick was this ever fixed?

**Comment by Fornax96** [comment]
Still getting it sometimes on the latest master build. But it's less frequent than in 1.2.2

**Comment by tbenz9** [comment]
Duplicate of #2346 

Recommendation to devs: Close
