### ISSUE TITLE
Siad has exited unexpectedly (on Ubuntu Linux) 

### ISSUE THREAD

**Issue by rstephe** [NebulousLabs/Sia#1837]
After more than 20 hours running for the first time, Sia GUI had synchronized only 42% and then threw the following error (log follows):
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 0.310817624 seconds

Wallet: scanned to height 1638...
Done!
2017/05/24 23:31:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
...
2017/05/25 08:56:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/25 08:56:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
goroutine 1380556 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc424d02c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc424d02e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42033a8a0, 0xc424d02e78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4215547f0, 0xc4202ca788, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
goroutine 1380555 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc426386d68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc426386ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42033a8a0, 0xc426386ec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc4215547f0, 0xc4202ca788)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: ERROR: unable to create write-ahead-log: open /home/rstephe/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files
Severe error: Unable to open temporary settings file for writing: open /home/rstephe/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
goroutine 1380556 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc424d02c80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc424d02e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42033a8a0, 0xc424d02e58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4215547f0, 0xc4202ca788, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 1380556 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc424d02aa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc424d02c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc42033a8a0, 0xc424d02c18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4202ca788, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4215547f0, 0xc4202ca788, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
2017/05/25 08:56:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/25 08:56:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 1380556 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4202ca788, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc4215547f0, 0xc4202ca788, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by lf94** [comment]
Siad is opening too many files/keeping open too many file handles. I'm only subscribed to Sia's repo and don't know much about the process, but if it restarts at the place it left off, you should be able to finish it with a restart.

**Comment by lf94** [comment]
Make sure you are using Sia 1.2.2, which fixes this issue.

**Comment by rstephe** [comment]
Thx for the comments.  I should have added the versions:
Sia-UI 1.6.4
Sia      1.2.2

**Comment by johnathanhowell** [comment]
Where does the version say 1.6.4? What does the version say in the `About` plugin?

**Comment by johnathanhowell** [comment]
Looks like the fix for this bug we pushed to before the release inadvertently didn't make it into v1.2.2; we've updated the releases, you should be able to download v1.2.2 again and this bug will be gone.

**Comment by rstephe** [comment]
Thanks, Jonathan, I'm downlooading 1.22 and will try it again.
- Rob

**Comment by rstephe** [comment]
Thanks, Jonathan, I'm downlooading 1.22 and will try it again.
- Rob

**Comment by rstephe** [comment]
The new version of version 1.22 definitely works better, but the 'too many open files' error persists.  See log below:
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 1.938366067 seconds
2017/05/28 07:57:43 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/28 07:57:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/28 07:57:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/28 07:57:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/28 07:57:48 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:51 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:57:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:12 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:13 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:14 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 07:58:15 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/28 13:23:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/28 13:23:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/28 13:23:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:23:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:12 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:13 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:14 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:15 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:18 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:19 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:20 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:21 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:22 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:23 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:24 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:27 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:28 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:29 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:30 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:31 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:32 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:36 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:41 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:42 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:43 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:48 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:51 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:24:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:25:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:25:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:25:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 13:25:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:31 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:33 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 15:21:34 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/05/28 15:21:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/05/28 15:21:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/05/28 15:21:35 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/05/28 15:21:36 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:37 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:38 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:39 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:40 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:41 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:42 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:43 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:44 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:45 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:46 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:47 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:48 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:49 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:50 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:51 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:52 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:53 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:54 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:55 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:56 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:57 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:58 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:21:59 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:00 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:01 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:02 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:03 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:04 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:05 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:06 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:07 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:08 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:09 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:10 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:11 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:12 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:13 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:14 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:15 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:16 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/05/28 15:22:17 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
goroutine 1872404 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425d5fc80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425d5fe78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201fe940, 0xc425d5fe78, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422a43af0, 0xc4200a8308, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:196 +0x236
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: ERROR: unable to create write-ahead-log: open /home/rstephe/.config/Sia-UI/sia/host/contractmanager/contractmanager.wal_temp: too many open files
goroutine 1872403 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc420afed68)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc420afeec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201fe940, 0xc420afeec0, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func1(0xc422a43af0, 0xc4200a8308)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:167 +0x227
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:184 +0x15d
Severe error: Unable to open temporary settings file for writing: open /home/rstephe/.config/Sia-UI/sia/host/contractmanager/contractmanager.json_temp: too many open files
goroutine 1872404 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425d5fc80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425d5fe58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201fe940, 0xc425d5fe58, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422a43af0, 0xc4200a8308, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:201 +0x357
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to properly initialize WAL file, crashing to prevent corruption: unable to write WAL metadata: invalid argument
goroutine 1872404 [running]:
runtime/debug.Stack(0x445617, 0x0, 0xc425d5faa0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/NebulousLabs/Sia/build.Severe(0xc425d5fc18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x92
github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc4201fe940, 0xc425d5fc18, 0x2, 0x2)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe0
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200a8308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:151 +0x46e
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422a43af0, 0xc4200a8308, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5
Severe error: Unable to write state change to WAL: invalid argument
panic: unable to append a change to the WAL, crashing to prevent corruption

goroutine 1872404 [running]:
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).appendChange(0xc4200a8308, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlog.go:152 +0x4b8
github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit.func2(0xc422a43af0, 0xc4200a8308, 0x0, 0x0, 0x0, 0xebc2b0, 0x0, 0x0)
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:208 +0x423
created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit
	/home/jrh/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:209 +0x1e5

**Comment by rstephe** [comment]
BTW, @johnathanhowell, the GUI version is shown as 1.22 when I go to About in the GUI itself, but is listed as 1.6.4 in the version file in the Sia-UI directory

**Comment by rstephe** [comment]
It took nearly 2 weeks and uncountable restarts of Sia-UI to completely synchronize.  This seems to be very slow for a fairly recent blockchain (when was its genesis block?
In any case, that did not stop the "too many open files" errors:

> Siad has exited unexpectedly. Please submit a bug report including the error log here.
Block height  108102
Entire error log follows (it did not contain a traceback):
> Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 671.793900426 seconds
2017/06/06 17:14:22 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:25 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 5ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 10ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 20ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 40ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 80ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 160ms
2017/06/06 17:14:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 320ms
2017/06/06 17:14:27 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 640ms
2017/06/06 17:14:27 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s
... <600 similar lines deleted>
2017/06/06 17:24:26 http: Accept error: accept tcp 127.0.0.1:9980: accept4: too many open files; retrying in 1s

**Comment by johnathanhowell** [comment]
what are your system specs like? Currently, Sia is heavily IO-bound and will perform far better on systems with SSDs

**Comment by rstephe** [comment]
@johnathanhowell I installed  the Sia files in my home directory, so it is running on a 1 TB 5400 RPM SATA III Hybrid Hard Drive with 8 GB SSD.  If I installed it as root it could run on a SSD if you thank that would make a big difference.

**Comment by lukechampine** [comment]
duplicate of #1840
